### ISSUE TITLE
I installed on my mac and try download course, but it seems doesn't work

### ISSUE THREAD

**Issue by FeitianSmartcardReader** [yoonwaiyan/stackskills-dl#31]
attachment is log, please have a look and help on this, thanks
[log.pdf](https://github.com/yoonwaiyan/stackskills-dl/files/1237923/log.pdf)

**Comment by yoonwaiyan** [comment]
May I know the contents inside the course? A screenshot inside one of the lecture for example, to know is there any video available to download as mp4 or a Wistia video etc.

**Comment by yoonwaiyan** [comment]
Will close this issue for now since there's no response, feel free to re-open the issue if there's any update.

**Comment by pouriraj** [comment]
Hi
I'm getting the same error.
and here is a screenshot from my course
thanks in advance

<img width="2143" alt="Screen Shot 1398-02-24 at 17 36 36" src="https://user-images.githubusercontent.com/50625577/57700280-e14e5c80-766e-11e9-96f7-a9824ac0011e.png">

**Comment by yoonwaiyan** [comment]
@pouriraj Please ensure youtube-dl is installed if you're not using Docker.

**Comment by pouriraj** [comment]
I'm using Docker and this is the log of my attempt:
[Log.pdf](https://github.com/yoonwaiyan/stackskills-dl/files/3179855/Log.pdf)

**Comment by yoonwaiyan** [comment]
@pouriraj may I know in general which file format are those failed lectures? Apparently they are quizzes which is probably a direct Q&A page?

**Comment by pouriraj** [comment]
I couldn't download anything at all
the script creates folders and subfolders but nothing else, they are all empty.

**Comment by yoonwaiyan** [comment]
I definitely understand that the folders are empty. My last reply refers to
the lectures on stackskills, because I don’t have access to your courses
and I don’t have any course with quiz. Please understand that other
platforms render quizzes as interactive HTML page, which will probably not
supported as it involves complications. For lectures other than quizzes
that are failed to download, I would like to know what are the file formats
so that I can guide you to do some custom coding to make it down loadable.
